/******************************************************************************/
/***               Generated by IBExpert 20/10/2019 11:04:01                ***/
/******************************************************************************/

/******************************************************************************/
/***      Following SET SQL DIALECT is just for the Database Comparer       ***/
/******************************************************************************/
SET SQL DIALECT 3;



/******************************************************************************/
/***                                 Tables                                 ***/
/******************************************************************************/



CREATE TABLE TAB_CLIENTE (
    CODIGO              VARCHAR(6) NOT NULL,
    NOME                VARCHAR(80),
    APELIDO             VARCHAR(50),
    ENDERECO            VARCHAR(80),
    BAIRRO              VARCHAR(30),
    CIDADE              VARCHAR(40),
    UF                  VARCHAR(2),
    CEP                 VARCHAR(10),
    COMPLEMENTO         VARCHAR(80),
    MORADIA             INTEGER,
    TIPO                VARCHAR(10),
    SITUACAO            INTEGER,
    TELEFONE1           VARCHAR(20),
    CELULAR             VARCHAR(20),
    EMAIL               VARCHAR(50),
    RG                  VARCHAR(25),
    CPF                 VARCHAR(18),
    ESTADOCIVIL         VARCHAR(15),
    DATA_CADASTRO       DATE,
    NASCIMENTO          VARCHAR(10),
    NUMERO              VARCHAR(10),
    RG_ORGAO            VARCHAR(5),
    RG_ESTADO           VARCHAR(2),
    RG_EMISSAO          DATE,
    SEXO                VARCHAR(1),
    HISTORICO           BLOB SUB_TYPE 0 SEGMENT SIZE 80,
    CNAE                VARCHAR(10),
    COD_MUNICIPIO_IBGE  VARCHAR(10),
    IBGE                VARCHAR(5),
    FOTO                VARCHAR(255),
    NACIONALIDADE       VARCHAR(60),
    PAIS                VARCHAR(60)
);




/******************************************************************************/
/***                              Primary Keys                              ***/
/******************************************************************************/

ALTER TABLE TAB_CLIENTE ADD CONSTRAINT PK_TAB_CLIENTE PRIMARY KEY (CODIGO);


/******************************************************************************/
/***                                Indices                                 ***/
/******************************************************************************/

CREATE INDEX APELIDO_CLI ON TAB_CLIENTE (APELIDO);
CREATE INDEX CPF_CLI ON TAB_CLIENTE (CPF);
CREATE INDEX NOME_CLI ON TAB_CLIENTE (NOME);


/******************************************************************************/
/***                               Privileges                               ***/
/******************************************************************************/
